openapi: 3.0.1
info:
  title: GenKwiz API
  description: Interactive quizzing API with questions of multiple engrossing genres.
  contact:
    name: Shriram Deshpande
    url: 'http://genkwiz.com'
    email: deshpandeshriram@gmail.com
  license:
    name: API License
    url: 'http://genkwiz.com'
  version: 0.0.2
servers:
  - url: 'http://localhost:8080/genkwiz/v1'
tags:
  - name: quiz-controller
    description: Quiz Controller
paths:
  /quizzes:
    post:
      tags:
        - quiz-controller
      description: creates quiz returns quizID.
      operationId: createQuiz
      parameters:
        - name: genre
          in: query
          description: genre of the question.
          required: true
          schema:
            type: string
        - name: mode
          in: query
          description: mode of the quiz.
          required: true
          schema:
            type: string
        - name: number
          in: query
          description: number of questions to fetch.
          required: false
          schema:
            type: integer
            minimum: 3
            maximum: 10
            default: 10
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    description: quiz id .
                    type: integer
                    format: int32
                  
          links:
            GetQuizByQuizId:
              description: >-
                The 'id' value returned in the response can be used as the
                'quizId' parameter in 'GET /quizzes/{quizId}'.
              operationId: getQuiz
              parameters:
                quizId: '$response.body#/id'
            
        '400':
          description: Bad Request 
        '401':
          description: Unauthorized
          content: {}
        '403':
          description: Forbidden
          content: {}
        '404':
          description: Not Found
          content: {}
        '500':
          description: Internal Server Error
          content: {}
  '/quizzes/{quizId}':
    get:
      tags:
        - quiz-controller
      description: fetch all the components of quiz.
      operationId: getQuiz
      parameters:
        - name: quizId
          in: path
          description: quizId
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Quiz'
        '401':
          description: Unauthorized
          content: {}
        '403':
          description: Forbidden
          content: {}
        '404':
          description: Not Found
          content: {}
      deprecated: false
   
  '/answers/{quizId}':
    post:
      tags:
        - quiz-controller
      description: submit and display correct answer .
      operationId: submitAnswer
      parameters:
        - name: quizId
          in: path
          description: Id of the quiz.
          required: true
          schema:
            type: string
        - name: questionId
          in: query
          description: Id of question whose answer is to be submitted.
          required: true
          schema:
            type: string
        - name: type
          in: query
          description: Type of the Question (MCQ/Subjective)
          required: true
          schema:
            type: string    
        - name: params
          in: query
          description: Details of attempted question 
          required: true
          schema:
            type: object
            properties:
              userTime:
                type: integer
              hintsUsed:
                type: integer
              scorePerQuestion:
                type: integer
              isAttempted:
                type: boolean
              userAnswer:
                type: string
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                items:
                 $ref : '#/components/schemas/Answer'  
         
            
        '400':
          description: Bad Request 
        '401':
          description: Unauthorized
          content: {}
        '403':
          description: Forbidden
          content: {}
        '404':
          description: Not Found
          content: {}
        '500':
          description: Internal Server Error
          content: {} 
          
  '/performance/{quizId}':
    get:
      tags:
        - quiz-controller
      description: Get the perfomance individual questions.
      operationId: getPerformance
      parameters:
        - name: quizId
          in: path
          description: Id of the quiz played.
          required: true
          schema:
            type: string
        
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                 userTime:
                  type: integer
                  format: int32
                 hintsUsed:
                  type: integer
                  format: int32
                 scorePerQuestion: 
                  type: integer
                  format: int32
                 isAttempted:
                  type: boolean
            
        '400':
          description: Bad Request 
        '401':
          description: Unauthorized
          content: {}
        '403':
          description: Forbidden
          content: {}
        '404':
          description: Not Found
          content: {}
        '500':
          description: Internal Server Error
          content: {}  
          
  '/score':
    post:
      tags:
        - quiz-controller
      description: Post performance of Entire Quiz.
      operationId: SubmitFinalPerformance.
      parameters:
        - name: quizId
          in: query
          description: Id of the quiz played.
          required: true
          schema:
            type: string
        
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  performanceId:
                    description: performance id .
                    type: integer
                    format: int32
            
                  
          links:
            GetPerformanceByPerformanceId:
              description: >-
                The 'performanceId' value returned in the response can be used as the
                'performanceId' parameter in 'GET /score/{performanceId}'.
              operationId: getScore
              parameters:
                performanceId: '$response.body#/performanceId'          
        '400':
          description: Bad Request 
        '401':
          description: Unauthorized
          content: {}
        '403':
          description: Forbidden
          content: {}
        '404':
          description: Not Found
          content: {}
        '500':
          description: Internal Server Error
          content: {} 
  '/score/{performanceId}':
    get:
      tags:
        - quiz-controller
      description: Post performance of Entire Quiz.
      operationId: getScore
      parameters:
        - name: performanceId
          in: path
          description: Performance id of quiz Played
          required: true
          schema:
            type: string
        
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref : '#/components/schemas/Performance'
        '400':
          description: Bad Request 
        '401':
          description: Unauthorized
          content: {}
        '403':
          description: Forbidden
          content: {}
        '404':
          description: Not Found
          content: {}
        '500':
          description: Internal Server Error
          content: {}       
components:
  schemas:
    Hint:
      title: Hint
      type: object
      properties:
        hintId:
          type: integer
          format: int32
        MediaType:
          $ref: '#/components/schemas/MultimediaH'
        Number:
          type: integer
          format: int32
        Value:
          type: string
        marksDeduction:
          type: integer
          format: int32
        questionId:
          $ref: '#/components/schemas/Question'
    Mode:
      title: Mode
      type: object
      properties:
        maxSore:
          type: integer
          format: int32
        maxTime:
          $ref: '#/components/schemas/Time'
        modeId:
          type: integer
          format: int32
        modeName:
          type: string
    MultimediaH:
      title: Multimedia in hint.
      type: object
      properties:
        Name:
          type: string
        multiType:
          type: string
        hintId:
          $ref: '#/components/schemas/Hint'
        multiId:
          type: integer
          format: int32  
        multicontent:
          type: string
          format: byte
          
          
    Multimedia:
      title: Multimedia in question.
      type: object
      properties:
        Name:
          type: string
        multiType:
          type: string
        questionId:
          $ref: '#/components/schemas/Question'
        numberOfMultimedia:
          type: integer
          format: int32
        multiId:
          type: integer
          format: int32
        multicontent:
          type: string
          format: byte
    Question:
      title: Question
      type: object
      properties:
        modeId:
          $ref: '#/components/schemas/Mode'
        Genre:
          type: string
        questionId:
          description: question id required to fetch answer in 'Answer'.
          type: integer
          format: int32
        Question:
          type: string
        Ratings:
          type: number
          format: float
        Type:
          type: string
    Answer:
      title: Answer of the question.
      type: object
      properties:
        questionId:
          $ref: '#/components/schemas/Question'
        answerValue:
          type: string
    Quiz:
      title: Quiz
      type: object
      properties:
        attempted:
          type: boolean
        hint:
          $ref: '#/components/schemas/Hint'
        multimediah:
           $ref: '#/components/schemas/MultimediaH'
        mode:
          $ref: '#/components/schemas/Mode'
        multimediaq:
          $ref: '#/components/schemas/Multimedia'
        numberofHints:
          $ref: '#/components/schemas/Hint'
        question:
          $ref: '#/components/schemas/Question'
        quizId:
          type: integer
          format: int32
        scorePerQuestion:
          type: integer
          format: int32
        userTime:
          type: integer
          format: int32
        isAttempted:
          type: boolean
    Time:
      title: Time
      type: string
      format: date-time
      description: Creation date and time
      
    Performance:
      title: Performance
      type: object
      properties:
        numberOfCorrect:
          type: integer
          format: int32 
        performanceId:
          type: integer
          format: int32
        quizId:
          type: integer
          format: int32  
        numberOfAttempted:
          type: integer
          format: int32
        totalTime:
          type: integer
          format: int32
        finalScore:
          type: integer
          format: int32
