swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
host: 'localhost:8080'
basePath: /
tags:
  - name: question-controller
    description: Question Controller
paths:
  /questions/all:
    get:
      tags:
        - question-controller
      summary: Get all Questions
      operationId: getAllQuestionsUsingGET
      produces:
        - '*/*'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Question'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /questions/post:
    post:
      tags:
        - question-controller
      summary: Post new Questions
      description: Post new questions to db
      operationId: addQuestionUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: q
          description: q
          required: true
          schema:
            $ref: '#/definitions/Question'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Question'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  '/questions/{hint2}':
    get:
      tags:
        - question-controller
      summary: Get all Questions of particular genre
      description: Type in the genre and get all questions of the genre entered
      operationId: getQuestionUsingGET
      produces:
        - '*/*'
      parameters:
        - name: hint2
          in: path
          description: hint2
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Question'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
    put:
      tags:
        - question-controller
      summary: Update the questions of particular type
      operationId: updateQuestionUsingPUT
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: hint2
          in: path
          description: hint2
          required: true
          type: string
        - in: body
          name: q
          description: q
          required: true
          schema:
            $ref: '#/definitions/Question'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Question'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
    delete:
      tags:
        - question-controller
      summary: Delete Questions of particular type
      operationId: deleteQuestionUsingDELETE
      produces:
        - '*/*'
      parameters:
        - name: hint2
          in: path
          description: hint2
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Question'
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      deprecated: false
definitions:
  Question:
    type: object
    properties:
      hint1:
        type: string
      hint2:
        type: string
      hint3:
        type: string
      q_id:
        type: integer
        format: int32
      quest:
        type: string
      story:
        type: string
      sub_ques:
        type: string
    title: Question
