management:
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: metrics
  health:
    db:
      enabled: true
    defaults:
      enabled: true
  security:
    enabled: false
spring:
  datasource:
    password: genkwiz
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
